// Mock data for development without backend
export const mockFlights = [
  // Delhi routes
  { id: 1,  airline: "Air India",  flightNumber: "AI-202",  origin: "Delhi",     destination: "Mumbai",     departureTime: "06:00", arrivalTime: "08:15", duration: "2h 15m", price: 4500,  class: "Economy",  seatsAvailable: 45 },
  { id: 2,  airline: "IndiGo",     flightNumber: "6E-101",  origin: "Delhi",     destination: "Mumbai",     departureTime: "09:30", arrivalTime: "11:45", duration: "2h 15m", price: 3800,  class: "Economy",  seatsAvailable: 32 },
  { id: 3,  airline: "Vistara",    flightNumber: "UK-876",  origin: "Delhi",     destination: "Mumbai",     departureTime: "14:00", arrivalTime: "16:10", duration: "2h 10m", price: 5800,  class: "Business", seatsAvailable: 12 },
  { id: 4,  airline: "SpiceJet",   flightNumber: "SG-301",  origin: "Delhi",     destination: "Bangalore",  departureTime: "07:15", arrivalTime: "09:50", duration: "2h 35m", price: 4200,  class: "Economy",  seatsAvailable: 50 },
  { id: 5,  airline: "IndiGo",     flightNumber: "6E-505",  origin: "Delhi",     destination: "Bangalore",  departureTime: "11:00", arrivalTime: "13:40", duration: "2h 40m", price: 3900,  class: "Economy",  seatsAvailable: 28 },
  { id: 6,  airline: "Air India",  flightNumber: "AI-504",  origin: "Delhi",     destination: "Chennai",    departureTime: "06:45", arrivalTime: "09:30", duration: "2h 45m", price: 5100,  class: "Economy",  seatsAvailable: 38 },
  { id: 7,  airline: "Vistara",    flightNumber: "UK-312",  origin: "Delhi",     destination: "Hyderabad",  departureTime: "08:30", arrivalTime: "11:00", duration: "2h 30m", price: 4700,  class: "Economy",  seatsAvailable: 22 },
  { id: 8,  airline: "IndiGo",     flightNumber: "6E-701",  origin: "Delhi",     destination: "Kolkata",    departureTime: "10:00", arrivalTime: "12:15", duration: "2h 15m", price: 4100,  class: "Economy",  seatsAvailable: 41 },
  { id: 9,  airline: "SpiceJet",   flightNumber: "SG-412",  origin: "Delhi",     destination: "Goa",        departureTime: "13:20", arrivalTime: "15:50", duration: "2h 30m", price: 5500,  class: "Economy",  seatsAvailable: 18 },
  { id: 10, airline: "Air India",  flightNumber: "AI-670",  origin: "Delhi",     destination: "Kochi",      departureTime: "07:00", arrivalTime: "10:15", duration: "3h 15m", price: 6200,  class: "Economy",  seatsAvailable: 29 },
  // Mumbai routes
  { id: 11, airline: "IndiGo",     flightNumber: "6E-345",  origin: "Mumbai",    destination: "Bangalore",  departureTime: "14:30", arrivalTime: "16:00", duration: "1h 30m", price: 3200,  class: "Economy",  seatsAvailable: 28 },
  { id: 12, airline: "Air India",  flightNumber: "AI-605",  origin: "Mumbai",    destination: "Delhi",      departureTime: "08:00", arrivalTime: "10:10", duration: "2h 10m", price: 4600,  class: "Economy",  seatsAvailable: 35 },
  { id: 13, airline: "Vistara",    flightNumber: "UK-440",  origin: "Mumbai",    destination: "Delhi",      departureTime: "16:45", arrivalTime: "18:55", duration: "2h 10m", price: 5900,  class: "Business", seatsAvailable: 8  },
  { id: 14, airline: "SpiceJet",   flightNumber: "SG-220",  origin: "Mumbai",    destination: "Chennai",    departureTime: "07:30", arrivalTime: "09:30", duration: "2h 00m", price: 3700,  class: "Economy",  seatsAvailable: 47 },
  { id: 15, airline: "IndiGo",     flightNumber: "6E-210",  origin: "Mumbai",    destination: "Hyderabad",  departureTime: "11:15", arrivalTime: "13:00", duration: "1h 45m", price: 3400,  class: "Economy",  seatsAvailable: 33 },
  { id: 16, airline: "Air India",  flightNumber: "AI-780",  origin: "Mumbai",    destination: "Kolkata",    departureTime: "09:00", arrivalTime: "11:30", duration: "2h 30m", price: 4900,  class: "Economy",  seatsAvailable: 21 },
  { id: 17, airline: "GoAir",      flightNumber: "G8-115",  origin: "Mumbai",    destination: "Goa",        departureTime: "06:30", arrivalTime: "07:40", duration: "1h 10m", price: 2800,  class: "Economy",  seatsAvailable: 55 },
  { id: 18, airline: "IndiGo",     flightNumber: "6E-320",  origin: "Mumbai",    destination: "Kochi",      departureTime: "15:00", arrivalTime: "16:40", duration: "1h 40m", price: 3600,  class: "Economy",  seatsAvailable: 40 },
  // Bangalore routes
  { id: 19, airline: "Vistara",    flightNumber: "UK-566",  origin: "Bangalore", destination: "Delhi",      departureTime: "06:00", arrivalTime: "08:45", duration: "2h 45m", price: 5200,  class: "Economy",  seatsAvailable: 30 },
  { id: 20, airline: "IndiGo",     flightNumber: "6E-420",  origin: "Bangalore", destination: "Mumbai",     departureTime: "10:00", arrivalTime: "11:30", duration: "1h 30m", price: 3100,  class: "Economy",  seatsAvailable: 44 },
  { id: 21, airline: "Air India",  flightNumber: "AI-812",  origin: "Bangalore", destination: "Chennai",    departureTime: "08:45", arrivalTime: "09:45", duration: "1h 00m", price: 2500,  class: "Economy",  seatsAvailable: 52 },
  { id: 22, airline: "SpiceJet",   flightNumber: "SG-530",  origin: "Bangalore", destination: "Hyderabad",  departureTime: "13:30", arrivalTime: "14:45", duration: "1h 15m", price: 2900,  class: "Economy",  seatsAvailable: 36 },
  { id: 23, airline: "IndiGo",     flightNumber: "6E-610",  origin: "Bangalore", destination: "Kolkata",    departureTime: "07:00", arrivalTime: "09:30", duration: "2h 30m", price: 4400,  class: "Economy",  seatsAvailable: 25 },
  { id: 24, airline: "GoAir",      flightNumber: "G8-214",  origin: "Bangalore", destination: "Goa",        departureTime: "16:00", arrivalTime: "17:10", duration: "1h 10m", price: 2700,  class: "Economy",  seatsAvailable: 48 },
  { id: 25, airline: "Vistara",    flightNumber: "UK-680",  origin: "Bangalore", destination: "Kochi",      departureTime: "09:30", arrivalTime: "10:30", duration: "1h 00m", price: 2600,  class: "Economy",  seatsAvailable: 60 },
  // Hyderabad routes
  { id: 26, airline: "IndiGo",     flightNumber: "6E-720",  origin: "Hyderabad", destination: "Delhi",      departureTime: "05:55", arrivalTime: "08:20", duration: "2h 25m", price: 4800,  class: "Economy",  seatsAvailable: 27 },
  { id: 27, airline: "Air India",  flightNumber: "AI-915",  origin: "Hyderabad", destination: "Mumbai",     departureTime: "11:30", arrivalTime: "13:15", duration: "1h 45m", price: 3500,  class: "Economy",  seatsAvailable: 39 },
  { id: 28, airline: "SpiceJet",   flightNumber: "SG-614",  origin: "Hyderabad", destination: "Bangalore",  departureTime: "15:45", arrivalTime: "17:00", duration: "1h 15m", price: 2800,  class: "Economy",  seatsAvailable: 43 },
  { id: 29, airline: "Vistara",    flightNumber: "UK-722",  origin: "Hyderabad", destination: "Chennai",    departureTime: "08:00", arrivalTime: "09:10", duration: "1h 10m", price: 2600,  class: "Economy",  seatsAvailable: 34 },
  { id: 30, airline: "IndiGo",     flightNumber: "6E-830",  origin: "Hyderabad", destination: "Goa",        departureTime: "12:00", arrivalTime: "13:15", duration: "1h 15m", price: 3100,  class: "Economy",  seatsAvailable: 20 },
  // Chennai routes
  { id: 31, airline: "Air India",  flightNumber: "AI-310",  origin: "Chennai",   destination: "Delhi",      departureTime: "06:30", arrivalTime: "09:20", duration: "2h 50m", price: 5300,  class: "Economy",  seatsAvailable: 31 },
  { id: 32, airline: "IndiGo",     flightNumber: "6E-910",  origin: "Chennai",   destination: "Mumbai",     departureTime: "10:45", arrivalTime: "12:45", duration: "2h 00m", price: 3900,  class: "Economy",  seatsAvailable: 46 },
  { id: 33, airline: "SpiceJet",   flightNumber: "SG-702",  origin: "Chennai",   destination: "Bangalore",  departureTime: "07:15", arrivalTime: "08:15", duration: "1h 00m", price: 2400,  class: "Economy",  seatsAvailable: 58 },
  { id: 34, airline: "Vistara",    flightNumber: "UK-850",  origin: "Chennai",   destination: "Kolkata",    departureTime: "14:00", arrivalTime: "16:10", duration: "2h 10m", price: 4600,  class: "Economy",  seatsAvailable: 23 },
  { id: 35, airline: "Air India",  flightNumber: "AI-430",  origin: "Chennai",   destination: "Kochi",      departureTime: "16:30", arrivalTime: "17:30", duration: "1h 00m", price: 2300,  class: "Economy",  seatsAvailable: 62 },
  // Kolkata routes
  { id: 36, airline: "IndiGo",     flightNumber: "6E-112",  origin: "Kolkata",   destination: "Delhi",      departureTime: "05:30", arrivalTime: "07:45", duration: "2h 15m", price: 4300,  class: "Economy",  seatsAvailable: 36 },
  { id: 37, airline: "Air India",  flightNumber: "AI-545",  origin: "Kolkata",   destination: "Mumbai",     departureTime: "09:15", arrivalTime: "11:45", duration: "2h 30m", price: 5000,  class: "Economy",  seatsAvailable: 28 },
  { id: 38, airline: "SpiceJet",   flightNumber: "SG-812",  origin: "Kolkata",   destination: "Bangalore",  departureTime: "12:30", arrivalTime: "15:00", duration: "2h 30m", price: 4500,  class: "Economy",  seatsAvailable: 19 },
  { id: 39, airline: "Vistara",    flightNumber: "UK-960",  origin: "Kolkata",   destination: "Chennai",    departureTime: "08:00", arrivalTime: "10:10", duration: "2h 10m", price: 4700,  class: "Economy",  seatsAvailable: 24 },
  // Goa routes
  { id: 40, airline: "IndiGo",     flightNumber: "6E-512",  origin: "Goa",       destination: "Delhi",      departureTime: "10:30", arrivalTime: "13:00", duration: "2h 30m", price: 5400,  class: "Economy",  seatsAvailable: 16 },
  { id: 41, airline: "GoAir",      flightNumber: "G8-320",  origin: "Goa",       destination: "Mumbai",     departureTime: "08:00", arrivalTime: "09:10", duration: "1h 10m", price: 2900,  class: "Economy",  seatsAvailable: 50 },
  { id: 42, airline: "SpiceJet",   flightNumber: "SG-923",  origin: "Goa",       destination: "Bangalore",  departureTime: "15:00", arrivalTime: "16:10", duration: "1h 10m", price: 2700,  class: "Economy",  seatsAvailable: 37 },
  // Kochi routes
  { id: 43, airline: "Air India",  flightNumber: "AI-760",  origin: "Kochi",     destination: "Delhi",      departureTime: "06:45", arrivalTime: "10:00", duration: "3h 15m", price: 6100,  class: "Economy",  seatsAvailable: 22 },
  { id: 44, airline: "IndiGo",     flightNumber: "6E-615",  origin: "Kochi",     destination: "Mumbai",     departureTime: "14:00", arrivalTime: "15:40", duration: "1h 40m", price: 3700,  class: "Economy",  seatsAvailable: 41 },
  { id: 45, airline: "Vistara",    flightNumber: "UK-488",  origin: "Kochi",     destination: "Bangalore",  departureTime: "09:00", arrivalTime: "10:00", duration: "1h 00m", price: 2700,  class: "Economy",  seatsAvailable: 55 },
  // Jaipur routes
  { id: 46, airline: "IndiGo",     flightNumber: "6E-219",  origin: "Jaipur",    destination: "Mumbai",     departureTime: "07:00", arrivalTime: "09:00", duration: "2h 00m", price: 3800,  class: "Economy",  seatsAvailable: 30 },
  { id: 47, airline: "Air India",  flightNumber: "AI-318",  origin: "Jaipur",    destination: "Bangalore",  departureTime: "11:30", arrivalTime: "14:10", duration: "2h 40m", price: 4600,  class: "Economy",  seatsAvailable: 25 },
  // Pune routes
  { id: 48, airline: "SpiceJet",   flightNumber: "SG-614",  origin: "Pune",      destination: "Delhi",      departureTime: "08:30", arrivalTime: "10:45", duration: "2h 15m", price: 4400,  class: "Economy",  seatsAvailable: 33 },
  { id: 49, airline: "IndiGo",     flightNumber: "6E-727",  origin: "Pune",      destination: "Bangalore",  departureTime: "13:00", arrivalTime: "14:30", duration: "1h 30m", price: 3200,  class: "Economy",  seatsAvailable: 42 },
  // Ahmedabad routes
  { id: 50, airline: "Air India",  flightNumber: "AI-412",  origin: "Ahmedabad", destination: "Delhi",      departureTime: "06:15", arrivalTime: "07:55", duration: "1h 40m", price: 3600,  class: "Economy",  seatsAvailable: 38 },
  { id: 51, airline: "IndiGo",     flightNumber: "6E-824",  origin: "Ahmedabad", destination: "Mumbai",     departureTime: "09:45", arrivalTime: "11:10", duration: "1h 25m", price: 2900,  class: "Economy",  seatsAvailable: 51 },
  { id: 52, airline: "IndiGo",     flightNumber: "6E-316",  origin: "Ahmedabad", destination: "Bangalore",  departureTime: "15:30", arrivalTime: "17:30", duration: "2h 00m", price: 4100,  class: "Economy",  seatsAvailable: 27 },
];

export const mockBuses = [
  {
    id: 1,
    operator: "VRL Travels",
    busNumber: "VRL-456",
    origin: "Bangalore",
    destination: "Mumbai",
    departureTime: "2026-04-10T22:00:00",
    arrivalTime: "2026-04-11T14:00:00",
    price: 1200,
    seatsAvailable: 25,
    busType: "Sleeper",
    amenities: ["AC", "WiFi", "Charging Port", "Water Bottle"],
    duration: "16h",
  },
  {
    id: 2,
    operator: "RedBus",
    busNumber: "RB-789",
    origin: "Delhi",
    destination: "Jaipur",
    departureTime: "2026-04-10T08:00:00",
    arrivalTime: "2026-04-10T13:30:00",
    price: 800,
    seatsAvailable: 18,
    busType: "Semi-Sleeper",
    amenities: ["AC", "Charging Port", "Entertainment"],
    duration: "5h 30m",
  },
  {
    id: 3,
    operator: "Orange Travels",
    busNumber: "OT-234",
    origin: "Hyderabad",
    destination: "Bangalore",
    departureTime: "2026-04-10T23:00:00",
    arrivalTime: "2026-04-11T07:00:00",
    price: 950,
    seatsAvailable: 30,
    busType: "Sleeper",
    amenities: ["AC", "WiFi", "Blanket", "Water Bottle"],
    duration: "8h",
  },
  {
    id: 4,
    operator: "SRS Travels",
    busNumber: "SRS-567",
    origin: "Chennai",
    destination: "Coimbatore",
    departureTime: "2026-04-10T21:30:00",
    arrivalTime: "2026-04-11T05:30:00",
    price: 750,
    seatsAvailable: 22,
    busType: "Sleeper",
    amenities: ["AC", "Charging Port", "Snacks"],
    duration: "8h",
  },
];

export const mockHotels = [
  {
    id: 1,
    name: "Taj Palace",
    location: "Mumbai",
    rating: 5,
    stars: 5,
    pricePerNight: 8500,
    amenities: ["Pool", "Spa", "Gym", "Restaurant", "Free WiFi"],
    imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
    description: "Luxury 5-star hotel with ocean view",
    availableRooms: 12,
    reviewCount: 450,
  },
  {
    id: 2,
    name: "Oberoi Grand",
    location: "Kolkata",
    rating: 5,
    stars: 5,
    pricePerNight: 7500,
    amenities: ["Pool", "Spa", "Restaurant", "Bar", "Free WiFi"],
    imageUrl: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800",
    description: "Heritage luxury hotel in the heart of Kolkata",
    availableRooms: 8,
    reviewCount: 380,
  },
  {
    id: 3,
    name: "Lemon Tree Hotel",
    location: "Bangalore",
    rating: 4,
    stars: 4,
    pricePerNight: 4500,
    amenities: ["Restaurant", "Gym", "Free WiFi", "Conference Room"],
    imageUrl: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800",
    description: "Modern business hotel with great amenities",
    availableRooms: 20,
    reviewCount: 520,
  },
  {
    id: 4,
    name: "Sea Shell Resort",
    location: "Goa",
    rating: 4,
    stars: 4,
    pricePerNight: 6000,
    amenities: ["Beach Access", "Pool", "Restaurant", "Water Sports", "Free WiFi"],
    imageUrl: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800",
    description: "Beachfront resort with amazing sunset views",
    availableRooms: 15,
    reviewCount: 340,
  },
];

export const mockPackages = [
  {
    id: 1,
    name: "Goa Beach Paradise",
    destination: "Goa",
    duration: 5,
    price: 15000,
    originalPrice: 20000,
    type: "Beach",
    description: "5 days of sun, sand, and sea",
    inclusions: ["Hotel", "Breakfast", "Airport Transfer", "Beach Activities"],
    imageUrl: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800",
    rating: 4.5,
  },
  {
    id: 2,
    name: "Rajasthan Royal Tour",
    destination: "Rajasthan",
    duration: 7,
    price: 25000,
    originalPrice: 32000,
    type: "Cultural",
    description: "Explore the royal heritage of Rajasthan",
    inclusions: ["Hotel", "All Meals", "Sightseeing", "Guide"],
    imageUrl: "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800",
    rating: 4.8,
  },
  {
    id: 3,
    name: "Kashmir Valley Adventure",
    destination: "Kashmir",
    duration: 6,
    price: 28000,
    type: "Adventure",
    description: "Experience the beauty of paradise on earth",
    inclusions: ["Hotel", "Breakfast & Dinner", "Shikara Ride", "Gondola Ride"],
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
    rating: 4.7,
  },
  {
    id: 4,
    name: "Kerala Backwaters Cruise",
    destination: "Kerala",
    duration: 4,
    price: 18000,
    originalPrice: 22000,
    type: "Relaxation",
    description: "Peaceful houseboat experience in Kerala",
    inclusions: ["Houseboat Stay", "All Meals", "Sightseeing", "Ayurvedic Massage"],
    imageUrl: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800",
    rating: 4.6,
  },
];

export const mockDestinations = [
  {
    id: 1,
    name: "Goa",
    country: "India",
    imageUrl: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800",
    packageCount: 12,
    startingPrice: 8000,
  },
  {
    id: 2,
    name: "Kashmir",
    country: "India",
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
    packageCount: 8,
    startingPrice: 15000,
  },
  {
    id: 3,
    name: "Rajasthan",
    country: "India",
    imageUrl: "https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800",
    packageCount: 15,
    startingPrice: 12000,
  },
  {
    id: 4,
    name: "Kerala",
    country: "India",
    imageUrl: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800",
    packageCount: 10,
    startingPrice: 10000,
  },
];

export const mockDeals = [
  {
    id: 1,
    title: "Goa Weekend Getaway",
    description: "3 nights at beach resort",
    imageUrl: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800",
    originalPrice: 12000,
    discountedPrice: 8400,
    discountPercent: 30,
    type: "package",
    referenceId: 1,
    validUntil: "2026-04-30",
  },
  {
    id: 2,
    title: "Mumbai-Delhi Flight Sale",
    description: "Special fare on select routes",
    imageUrl: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800",
    originalPrice: 6000,
    discountedPrice: 4200,
    discountPercent: 30,
    type: "flight",
    referenceId: 1,
    validUntil: "2026-04-25",
  },
  {
    id: 3,
    title: "Luxury Hotel Discount",
    description: "Stay at 5-star hotels for less",
    imageUrl: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800",
    originalPrice: 10000,
    discountedPrice: 6500,
    discountPercent: 35,
    type: "hotel",
    referenceId: 1,
    validUntil: "2026-05-15",
  },
];

export const mockStats = {
  totalBookings: 1250,
  happyCustomers: 980,
  destinations: 45,
  yearsExperience: 12,
};

// Mock bookings data
export const mockBookings = [
  {
    id: 1,
    bookingType: "flight" as const,
    referenceId: 1,
    passengerName: "John Doe",
    passengerEmail: "john@example.com",
    passengerPhone: "+1234567890",
    passengers: 2,
    travelDate: "2026-05-15",
    status: "confirmed" as const,
    createdAt: "2026-04-01T10:30:00Z",
    totalPrice: 9000,
    details: {
      title: "Delhi to Mumbai - Air India",
      description: "Economy class flight",
    },
  },
  {
    id: 2,
    bookingType: "hotel" as const,
    referenceId: 1,
    passengerName: "Jane Smith",
    passengerEmail: "jane@example.com",
    passengerPhone: "+9876543210",
    passengers: 1,
    travelDate: "2026-06-20",
    status: "confirmed" as const,
    createdAt: "2026-04-02T14:20:00Z",
    totalPrice: 17000,
    details: {
      title: "Taj Palace Mumbai - Deluxe Room",
      description: "2 nights stay with breakfast",
    },
  },
  {
    id: 3,
    bookingType: "bus" as const,
    referenceId: 2,
    passengerName: "Mike Johnson",
    passengerEmail: "mike@example.com",
    passengerPhone: "+1122334455",
    passengers: 3,
    travelDate: "2026-04-25",
    status: "pending" as const,
    createdAt: "2026-04-03T09:15:00Z",
    totalPrice: 2400,
    details: {
      title: "Delhi to Jaipur - RedBus",
      description: "Semi-Sleeper AC bus",
    },
  },
  {
    id: 4,
    bookingType: "package" as const,
    referenceId: 1,
    passengerName: "Sarah Williams",
    passengerEmail: "sarah@example.com",
    passengerPhone: "+5544332211",
    passengers: 4,
    travelDate: "2026-07-10",
    status: "confirmed" as const,
    createdAt: "2026-04-04T16:45:00Z",
    totalPrice: 60000,
    details: {
      title: "Goa Beach Paradise Package",
      description: "5 days all-inclusive beach vacation",
    },
  },
];
