import { useState, useEffect } from "react";
import { AdminLayout } from "@/components/admin-layout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { useToast } from "@/hooks/use-toast";
import {
  Search, Download, FileText, Plane, Building2,
  Bus, Map, RefreshCw, User, Phone, Mail,
  Calendar, CreditCard, IndianRupee,
} from "lucide-react";
import { getStoredInvoices, generateInvoicePDF, type StoredInvoice } from "@/lib/invoice";

const TYPE_ICON: Record<string, React.ElementType> = {
  flight:  Plane,
  hotel:   Building2,
  bus:     Bus,
  package: Map,
};

const TYPE_COLOR: Record<string, string> = {
  flight:  "bg-sky-100 text-sky-700",
  hotel:   "bg-teal-100 text-teal-700",
  bus:     "bg-orange-100 text-orange-700",
  package: "bg-purple-100 text-purple-700",
};

export default function AdminInvoices() {
  const [invoices, setInvoices] = useState<StoredInvoice[]>([]);
  const [search, setSearch] = useState("");
  const [filterType, setFilterType] = useState("all");
  const { toast } = useToast();

  function load() {
    setInvoices(getStoredInvoices());
  }

  useEffect(() => { load(); }, []);

  const filtered = invoices.filter((inv) => {
    const q = search.toLowerCase();
    const matchSearch =
      !q ||
      inv.bookingId.toLowerCase().includes(q) ||
      inv.passengerName.toLowerCase().includes(q) ||
      inv.passengerEmail.toLowerCase().includes(q) ||
      inv.invoiceNumber.toLowerCase().includes(q);
    const matchType = filterType === "all" || inv.bookingType === filterType;
    return matchSearch && matchType;
  });

  const totalRevenue = filtered.reduce((s, i) => s + i.totalAmount, 0);

  function handleDownload(inv: StoredInvoice) {
    generateInvoicePDF(inv);
    toast({ title: "Invoice Downloaded", description: `${inv.invoiceNumber} — ${inv.passengerName}` });
  }

  return (
    <AdminLayout>
      <div className="p-4 md:p-8 space-y-6">

        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div>
            <h1 className="text-2xl font-extrabold text-slate-900">Invoices</h1>
            <p className="text-slate-500 text-sm mt-0.5">
              All branded booking invoices generated by WanderWay
            </p>
          </div>
          <Button variant="outline" size="sm" onClick={load} className="gap-2 self-start sm:self-auto">
            <RefreshCw className="w-3.5 h-3.5" /> Refresh
          </Button>
        </div>

        {/* Stats */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          {[
            { label: "Total Invoices", value: invoices.length, icon: FileText, color: "text-blue-600", bg: "bg-blue-50" },
            { label: "Filtered Results", value: filtered.length, icon: Search, color: "text-purple-600", bg: "bg-purple-50" },
            { label: "Total Revenue", value: `₹${totalRevenue.toLocaleString("en-IN")}`, icon: IndianRupee, color: "text-green-600", bg: "bg-green-50" },
            { label: "This Month", value: invoices.filter(i => {
              const d = new Date(i.generatedAt);
              const now = new Date();
              return d.getMonth() === now.getMonth() && d.getFullYear() === now.getFullYear();
            }).length, icon: Calendar, color: "text-orange-600", bg: "bg-orange-50" },
          ].map(({ label, value, icon: Icon, color, bg }) => (
            <Card key={label} className="border-0 shadow-sm">
              <CardContent className="p-4 flex items-center gap-3">
                <div className={`w-9 h-9 rounded-xl ${bg} flex items-center justify-center shrink-0`}>
                  <Icon className={`w-4 h-4 ${color}`} />
                </div>
                <div>
                  <p className="text-xs text-slate-400">{label}</p>
                  <p className="text-base font-extrabold text-slate-900">{value}</p>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* Filters */}
        <div className="flex flex-col sm:flex-row gap-3">
          <div className="relative flex-1 max-w-sm">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
            <Input
              placeholder="Search by name, booking ID, invoice…"
              className="pl-9"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
            />
          </div>
          <div className="flex gap-2 flex-wrap">
            {["all", "flight", "hotel", "bus", "package"].map((t) => (
              <button
                key={t}
                onClick={() => setFilterType(t)}
                className={`px-3 py-1.5 rounded-lg text-xs font-semibold capitalize transition-all ${
                  filterType === t
                    ? "bg-slate-900 text-white"
                    : "bg-white border border-slate-200 text-slate-600 hover:border-slate-400"
                }`}
              >
                {t === "all" ? "All Types" : t}
              </button>
            ))}
          </div>
        </div>

        {/* Invoice list */}
        {filtered.length === 0 ? (
          <div className="text-center py-20 text-slate-400">
            <FileText className="w-10 h-10 mx-auto mb-3 opacity-30" />
            <p className="font-semibold text-slate-500">No invoices found</p>
            <p className="text-sm mt-1">Invoices are generated automatically after each booking</p>
          </div>
        ) : (
          <div className="space-y-3">
            {filtered.map((inv) => {
              const Icon = TYPE_ICON[inv.bookingType] ?? FileText;
              const badgeColor = TYPE_COLOR[inv.bookingType] ?? "bg-slate-100 text-slate-700";
              return (
                <Card key={inv.bookingId} className="border-0 shadow-sm hover:shadow-md transition-shadow">
                  <CardContent className="p-4 md:p-5">
                    <div className="flex flex-col md:flex-row md:items-center gap-4">

                      {/* Left: icon + IDs */}
                      <div className="flex items-start gap-3 flex-1 min-w-0">
                        <div className="w-10 h-10 rounded-xl bg-slate-100 flex items-center justify-center shrink-0">
                          <Icon className="w-5 h-5 text-slate-600" />
                        </div>
                        <div className="min-w-0">
                          <div className="flex items-center gap-2 flex-wrap">
                            <span className="font-bold text-slate-900 text-sm">{inv.invoiceNumber}</span>
                            <Badge className={`${badgeColor} text-xs capitalize`}>{inv.bookingType}</Badge>
                          </div>
                          <p className="text-xs text-slate-500 mt-0.5 truncate">{inv.title}</p>
                          <p className="text-xs text-slate-400 font-mono">{inv.bookingId}</p>
                        </div>
                      </div>

                      {/* Mid: customer */}
                      <div className="flex flex-col gap-0.5 min-w-[160px]">
                        <div className="flex items-center gap-1.5 text-sm text-slate-700 font-semibold">
                          <User className="w-3.5 h-3.5 text-slate-400" /> {inv.passengerName}
                        </div>
                        <div className="flex items-center gap-1.5 text-xs text-slate-400">
                          <Mail className="w-3 h-3" /> {inv.passengerEmail}
                        </div>
                        <div className="flex items-center gap-1.5 text-xs text-slate-400">
                          <Phone className="w-3 h-3" /> {inv.passengerPhone}
                        </div>
                      </div>

                      {/* Mid: dates */}
                      <div className="flex flex-col gap-0.5 min-w-[130px]">
                        <div className="flex items-center gap-1.5 text-xs text-slate-500">
                          <Calendar className="w-3 h-3" />
                          Travel: {new Date(inv.travelDate).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" })}
                        </div>
                        <div className="flex items-center gap-1.5 text-xs text-slate-400">
                          <CreditCard className="w-3 h-3" /> {inv.paymentId}
                        </div>
                        <div className="text-xs text-slate-400">
                          Issued: {new Date(inv.generatedAt).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" })}
                        </div>
                      </div>

                      {/* Right: amount + download */}
                      <div className="flex items-center gap-4 md:ml-auto">
                        <div className="text-right">
                          <p className="text-xs text-slate-400">Amount</p>
                          <p className="text-lg font-extrabold text-slate-900">₹{inv.totalAmount.toLocaleString("en-IN")}</p>
                        </div>
                        <Button
                          size="sm"
                          onClick={() => handleDownload(inv)}
                          className="gap-1.5 font-bold shrink-0"
                        >
                          <Download className="w-3.5 h-3.5" /> Download
                        </Button>
                      </div>

                    </div>
                  </CardContent>
                </Card>
              );
            })}
          </div>
        )}

      </div>
    </AdminLayout>
  );
}
